### ISSUE TITLE
扩展设置标签页打开时从图标启用扩展失效

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#11]
重现步骤：

1、打开本扩展设置标签（moz-extension://3f879fe5-b00d-4b1d-9a1a-15607d3909e3/options/options.html ），取消勾选“开启重定向”并保存。不要关闭该标签页；

2、点击扩展图标“R”，弹出选项，勾选“开启重定向”；

3、切换到前述标签页并刷新，或新打开一个本扩展设置标签，可见“开启重定向”依然没有勾选。但此时点开扩展图标“R”，可见“开启重定向”保持勾选状态。此时实际测试也可以确定本扩展未启用。

4、如果是之前为勾选状态，打开着本扩展设置标签页，从图标弹出菜单中取消勾选，则设置标签页会同步取消。

**Comment by fengyc** [comment]
我未能按照描述重现这个问题，可能我没有理解清楚，麻烦你详细描述过程，注意区分 firefox 扩展设置、插件弹出窗口、插件设置页面

**Comment by ivysrono** [comment]
@fengyc 更新了主楼。如果还不清楚，我上图。

**Comment by fengyc** [comment]
这个很有意思
