### ISSUE TITLE
增加规则测试功能

### ISSUE THREAD

**Issue by fengyc** [fengyc/URLRedirector#13]
增加规则测试功能，在规则创建时，允许加入一个 example ，同时对该 example 进行转换测试，便于及时发现规则的问题

**Comment by fengyc** [comment]
已在 v1.3.0 中实现

**Comment by ivysrono** [comment]
能不能加入多个example的啊？
感觉自己越来越贪心了ε=ε=ε=┏(゜ロ゜;)┛

**Comment by fengyc** [comment]
一般一个就足够了，起一个示例作用就好
