### ISSUE TITLE
能否增加 UpgradeMixedContent 功能

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#15]
功能来自：[UpgradeMixedContent 扩展](https://addons.mozilla.org/zh-CN/firefox/addon/upgrademixedcontent/)
简述：
main_frame 为 https 但页内有 http 资源时，浏览器会默认禁止主动性资源如 JS，目前还会放行被动型资源如 image，这一行为由浏览器完成，扩展基本不能干预。
昨天发现的 UpgradeMixedContent 扩展提供了目前仅见的干预思路：给所有的 http 资源插入一个 upgrade-insecure-requests ，这样浏览器就会尝试用 https 来访问本会被 MCB 的资源。
缺陷：
UpgradeMixedContent 扩展是默认全局使用的，于是部分资源，主要是图片就会被破坏，如 [好奇心日报](https://www.qdaily.com/articles/37594.html)
该扩展作者是个极端派，他认为没有加密的资源就不应该被载入。

建议：
本扩展重定向包含所有资源类型，能否加入该功能，这样我就能把部分页面默认重定向到 https 了，如 https://i.gtimg.cn/

HTTPS-Everywhere 也开始讨论这个问题了：https://github.com/EFForg/https-everywhere/issues/8506

**Comment by ivysrono** [comment]
https://github.com/gloomy-ghost/UpgradeMixedContent
Chrome版有了黑名单。
但直接打包成Firefox扩展的话没有设置页面。
另外没有白名单模式，误伤在所难免。

**Comment by fengyc** [comment]
从这个文档 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests 来看，需要在请求头部加上一个 Upgrade-Insecure-Requests ，应该可以实现的

**Comment by KrasnayaPloshchad** [comment]
现在暂时可以使用 [UpgradeMixedContentByBlacklist](https://addons.mozilla.org/zh-CN/firefox/addon/upgrademixedcontentbyblacklist/) 来代替
