### ISSUE TITLE
Bug: Firefox 52 开启“浏览器同步”导致设置被清空

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#19]
#3 这个选项应该在53才能被开启。52意外开启后，一旦勾选，过一会，设置全部清空。重新配置，再次清空。
不清楚在53开启后是否还会造成问题。

**Comment by fengyc** [comment]
我也碰到了这个问题，在开发者版本 firefox 53 上这个是正常的，这个地方不要点保存就不会保存设置，我在看到底是怎么回事
