### ISSUE TITLE
Cant get it to work - "storage is null"

### ISSUE THREAD

**Issue by joahim51** [fengyc/URLRedirector#20]
Hi there, sorry no chinese, using google translate to follow you. Found this plugin to be very forward-looking and it should cover most of my daily needs.

But I'm stuck at a very early stage of installing it to Firefox, tried offline 1.3.2 last release (https://github.com/fengyc/URLRedirector/blob/master/tools/urlredirector_offline-1.3.2-an%2Bfx.xpi)

I can't create rules, download rules (found that button using google translate :)), I always see "storage is null" and it's variations in console.
I tried installing on clean profile, then tried to manually enable in about:config every *storage* option, but still no luck.
Please help and advise, as I want this plugin for daily use and follow your Issues here though don't know chinese.. in forward maybe I can be usefull to translate menu at least to english.

This is what console shows in different versions of firefox, my last try to install it was few days ago:

===============51.0.1 release

Error: storage is null  (unknown)
TypeError: storage is null[Learn More]  options.js:499:9
	<anonymous> moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/options/options.js:499:9
	jQuery.event.dispatch moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/static/js/jquery.js:4736:16
	jQuery.event.add/elemData.handle moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/static/js/jquery.js:4549:6
TypeError: storage is null[Learn More] options.js:215:1
	displayAll moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/options/options.js:215:1
	<anonymous> moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/options/options.js:525:5
	jQuery.event.dispatch moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/static/js/jquery.js:4736:16
	jQuery.event.add/elemData.handle moz-extension://00eea6c7-4e0f-4a34-9d5d-e9a4244cb788/static/js/jquery.js:4549:6

===============52b9
storage is null background.js:139
	handleRedirect moz-extension://5832083b-dc46-4bb0-9bde-a9b30dbb3077/background.js:139:1
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeSync resource://gre/modules/ExtensionUtils.jsm:104:37
	runSafe resource://gre/modules/ExtensionCommon.jsm:123:32
	receiveMessage resource://gre/modules/ExtensionChild.jsm:586:49
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:574:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:573:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:637:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:634:24
	bound _handleMessage self-hosted:917:17
	receiveMessage resource://gre/modules/MessageChannel.jsm:165:5

TypeError: storage is null[Learn More]  options.js:150:22
	<anonymous> moz-extension://5832083b-dc46-4bb0-9bde-a9b30dbb3077/options/options.js:150:22
	jQuery.event.dispatch moz-extension://5832083b-dc46-4bb0-9bde-a9b30dbb3077/static/js/jquery.js:4736:16
	jQuery.event.add/elemData.handle moz-extension://5832083b-dc46-4bb0-9bde-a9b30dbb3077/static/js/jquery.js:4549:6

Error: storage is null  (unknown)

===============nightly 030517

storage is null background.js:139
	handleRedirect moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/background.js:139:1
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeSync resource://gre/modules/ExtensionUtils.jsm:104:37
	runSafe resource://gre/modules/ExtensionCommon.jsm:123:32
	receiveMessage resource://gre/modules/ExtensionChild.jsm:633:49
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:580:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:579:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:643:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:640:24
	bound _handleMessage self-hosted:915:17
	receiveMessage resource://gre/modules/MessageChannel.jsm:165:5

TypeError: storage is null[Learn More]  options.js:150:22
	<anonymous> moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/options/options.js:150:22
	dispatch moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/static/js/jquery.js:4736:16
	add/elemData.handle moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/static/js/jquery.js:4549:6

Error: storage is null (unknown)

TypeError: storage is null[Learn More]  options.js:499:9
	<anonymous> moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/options/options.js:499:9
	dispatch moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/static/js/jquery.js:4736:16
	add/elemData.handle moz-extension://45e88511-8a3a-499f-bd26-bd276faba481/static/js/jquery.js:4549:6

**Comment by fengyc** [comment]
@joahim51 Thanks for your feedback. It is a bug in v1.3.2 when I try to introduct storage.sync. I had  fixed it immediately after It was found in v1.3.3.  

Please download the latest URLRedirector from https://addons.mozilla.org/zh-CN/firefox/addon/urlredirector/ . The latest version v1.3.4 supports i18n, both chinese and english.

Thanks for your bug report :-)

**Comment by fengyc** [comment]
@joahim51 To translate the menu, please fork and modify https://github.com/fengyc/URLRedirector/tree/master/src/_locales/en , then send me a pull request.
