### ISSUE TITLE
Firefox 52 奇怪重定向行为和问题集合

### ISSUE THREAD

**Issue by fengyc** [fengyc/URLRedirector#21]
不知道这个是什么鬼，在重定向前，firefox 会先加载旧的url，如果旧的 url 无法访问就会重定向失败

https://bugzilla.mozilla.org/show_bug.cgi?id=1345893

**Comment by fengyc** [comment]
#19 storage.sync 文档有坑，firefox 52 上 storage.sync 是可用的，但需要配置

**Comment by ivysrono** [comment]
user_pref("webextensions.storage.sync.enabled", true); //https://github.com/fengyc/URLRedirector/issues/21

好坑……

**Comment by fengyc** [comment]
有其它人也被坑了 https://bugzilla.mozilla.org/show_bug.cgi?id=1346077
chrome 一直好好的。。。难道要转战 chrome ？

**Comment by gloomy-ghost** [comment]
@fengyc 好巧啊，那个bug是我提的……

**Comment by ivysrono** [comment]
我都想来召唤鬼兄了…

**Comment by fengyc** [comment]
👍 ...

**Comment by JerryJian** [comment]
改了配置还是去加载 googleapis，52版的32位64位都是这样的，是不是要等Openfire自己修复这个问题才行

**Comment by fengyc** [comment]
@JerryJian 目前来看要等这个问题处理掉才能正常使用，或者回退到 firefox 51 ... 我自己退回到 51 了

**Comment by JerryJian** [comment]
@fengyc 好的，我先用Chrome了，正好你的Chrome版本发布了，等Firefox更新了再用吧

**Comment by fengyc** [comment]
chrome 可用开发者模式，从 release https://github.com/fengyc/URLRedirector/releases 上下载下来解压就能加载使用

**Comment by fengyc** [comment]
重定向的 BUG 已被确认，https://bugzilla.mozilla.org/show_bug.cgi?id=1345893 
    status-firefox52:affected
    status-firefox53:affected
    status-firefox54:affected
    status-firefox55:affected
接下来就等吧。。。

**Comment by fengyc** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1345893#c43
影响太大，firefox 52 上可能不会修复这个 bug

**Comment by yfdyh000** [comment]
@fengyc 那个是批量标记错过提升周期的bug。

截至目前，没有[提升请求](https://wiki.mozilla.org/Release_Management/Uplift_rules)。Firefox 53的[合并日](https://wiki.mozilla.org/RapidRelease/Calendar)是2017-04-18。

**Comment by ivysrono** [comment]
我本来都在考虑直接用55了……原来还有加快途径啊。

@gloomy-ghost 你这样edit，邮件里看不见的，我来帮你一把~

**Comment by yfdyh000** [comment]
@gloomy-ghost 现在申请可能有点晚了。可以写在 [User impact if declined]，具体审批标准不明。因为有单元测试，所以通过几率可能大些。但因为不是广泛影响，所以不一定被批准。

**Comment by gloomy-ghost** [comment]
这个插件加上 https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/ 可以凑齐 1k 受影响用户… 一个是重定向速度大幅减慢甚至失败（如果原站已经挂掉的话），另一个是直接发送了 http 请求…

但是这个是不是得 assigns 来提？就算明天 mixedpuppy 早上就看到也不一定来得及吧😂

**Comment by ivysrono** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/redirector/
这个也是 WebExtesion，应该也受影响的，直接就是 10k 用户。

**Comment by yfdyh000** [comment]
那你们可以提出试试，写在[受影响]中。
没限定必须分配者提，只是分配者一般更了解补丁是否适合提升（比如有些可能不兼容之前版本）。
不一定来得及，只能碰碰运气。beta和aurora可以一起标，顶多错过一个。

**Comment by ivysrono** [comment]
昨天从 @yfdyh000 维护的 AMO WebExtension 收藏集中挖到了好几个宝，多谢多谢。

**Comment by xunxun1982** [comment]
52ESR还是有希望的 还是自己打补丁靠谱

**Comment by fengyc** [comment]
@yfdyh000 哦，我不是很了解 mozilla 的 bug 管理流程，惭愧，我只在 need info 时交了些测试代码，看 https://bugzilla.mozilla.org/show_bug.cgi?id=1345893#a3454413_580382 连 firefox 53 都是 wontfix ~

**Comment by yfdyh000** [comment]
@fengyc 因为Firefox 53今天发布了，这不是导致严重问题的bug，不适合提升补丁到Release。

**Comment by JerryJian** [comment]
53也不修复么，有没有其他重定向方法绕过这个BUG，已经用了一个月Chrome了，还是想用火狐

**Comment by ivysrono** [comment]
等楼上大大出pcxfirefox编译版

**Comment by gloomy-ghost** [comment]
Fx54 已经给批准了，到 beta 等推送吧

**Comment by KrasnayaPloshchad** [comment]
Fx54 已经进了 beta 通道，去 [FTP 服务器](https://ftp.mozilla.org/pub/firefox/releases/)看看 😁

**Comment by ivysrono** [comment]
54已经推送，问题已经解决，可以close了。

**Comment by fengyc** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1345893
最新的 bug 动态上已处理了此问题
