### ISSUE TITLE
使用 storage.sync 支持多个浏览器的配置同步

### ISSUE THREAD

**Issue by fengyc** [fengyc/URLRedirector#3]
在支持 storage.sync 的浏览器上，开启同步配置选项，以支持多个浏览器之间的同步

**Comment by ivysrono** [comment]
Firefox上没有同步成功，才反应过来这个issue为何还没有关掉……

**Comment by fengyc** [comment]
firefox Webextension 还不成熟，storage.sync 的 api 还未开发，https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync ，这个支持要延后等待 storage.sync 实现了才能做

**Comment by ivysrono** [comment]
其实有变通之法的：
https://github.com/violentmonkey/violentmonkey/issues/51

**Comment by fengyc** [comment]
通过云盘等进行同步是个很好的方式，在后续的版本中会进行添加

**Comment by gloomy-ghost** [comment]
Firefox 53 实现了 storage.sync，五天后将进入β版

**Comment by ivysrono** [comment]
云盘同步有其独特意义：跨浏览器

**Comment by fengyc** [comment]
计划在 1.3.2 中实现 storage.sync ，云盘的同步看来不来得及，毕竟还要看看各个主流云盘的 RESTful sdk
