### ISSUE TITLE
配置页点击“重置”“下载”两个按钮无反应

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [fengyc/URLRedirector#37]
现在在配置页点击“重置”或者“下载”按钮以后都无法更改配置。版本 1.3.11，使用 [jsDelivr 源](https://cdn.jsdelivr.net/gh/fengyc/URLRedirector@master/tools/rules.json)，Chrome 70 和 Firefox 63 都能重现。

**Comment by fengyc** [comment]
@KrasnayaPloshchad  你能打开 console 把里面错误贴上来吗，我没能重现问题

**Comment by KrasnayaPloshchad** [comment]
这次发现，卸载以后重新安装，配置好在线规则 URL，点击下载按钮就会卡在“正在下载在线规则”那儿了。

**Comment by fengyc** [comment]
试了好多次，没法重现，麻烦你查一下时不是把对应的 url 给拦截了。同时生成一个 1.3.15 的版本，你可以试试

**Comment by KrasnayaPloshchad** [comment]
看不到哪个 url 被拦截了。打开选项以后我在火狐控制台里面看到下面的信息：
```
源映射错误：TypeError: NetworkError when attempting to fetch resource.
源 URL：moz-extension://a64db976-f15c-442a-9627-48afb411dbaf/static/css/bootstrap.min.css
源映射 URL：bootstrap.min.css.map[详细了解]
```
然后我添加在线规则 URL，点击保存，就得到下面的消息：
`Unknown method                                                        options.js:424:9`
最后点击下载按钮，完事以后点击古 url 旁边的眼睛按钮看到的规则都是空的。

**Comment by fengyc** [comment]
SyntaxError: "JSON.parse: unexpected character at line 1 column 2 of the JSON data" 
[https://cdn.jsdelivr.net/gh/fengyc/URLRedirector@master/tools/rules.json](https://cdn.jsdelivr.net/gh/fengyc/URLRedirector@master/tools/rules.json)
这个 json 文件解析出错了，不是因为下载的问题

**Comment by KrasnayaPloshchad** [comment]
今天我点击下载键手动更新规则以后，打开 sbout:support 查看配置文件夹，发现 storage 里面没有写入任何规则。

**Comment by fengyc** [comment]
~挑好玩的，https://cdn.jsdelivr.net/gh/fengyc/URLRedirector@master/tools/rules.json 下下来的是直接就是一个 json 对象，已更新了

**Comment by KrasnayaPloshchad** [comment]
已解决，多谢。

**Comment by KrasnayaPloshchad** [comment]
希望能在 Chrome 应用店上也能看到新版
