### ISSUE TITLE
能否支持 Firefox for android？

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#4]
看amo上的适用范围，还是没有android。
Android上实在是没有好用的重定向扩展啊

**Comment by ivysrono** [comment]
额，发现#1 ，是支持的版本还没有提交到 amo？

**Comment by fengyc** [comment]
amo 的审核已经通过了，只是我测试时发现 firefox for  andriod 上运行时有问题，在 android 上很多的 api 有兼容问题，才把选项去掉了，下个版本可测试一下兼容性

**Comment by fengyc** [comment]
主要的问题还是在 api 兼容性上，firefox for android 上没有办法打开配置页面，只能暂时搁置。firefox 想全面转到 webextension ，但是又在各个平台上不兼容，很难搞~~，只能想其它办法

**Comment by ivysrono** [comment]
Redirector也是无法打开配置界面。
所以我对Httpseverywhere能在Android上无障碍运行很惊讶。
我还没搞明白Httpseverywhere怎么编译出最终xpi的，看来需要研究下自定义一个了…

**Comment by fengyc** [comment]
应该是还在用原来的 addon sdk ，按照 firefox 的说法，这种方式的插件会逐步弃用~~

**Comment by KrasnayaPloshchad** [comment]
能不能借鉴这个扩展的方式在菜单里面加一个链接。
https://addons.mozilla.org/zh-CN/android/addon/toggle-image-blocking/

**Comment by ivysrono** [comment]
打开lo页面有用是指？

**Comment by KrasnayaPloshchad** [comment]
最近一段时间跟这个项目的开发者打过交道，所以我就发现了这网站几乎全页文字都用谷歌的 web 字体，之前 gooreplacer 开发者没有搞定兼容 Android 的问题，所以需要到这网站时候颇费周折，安装这扩展以后就见到奇效。

**Comment by ivysrono** [comment]
如果还是不能打开设置页面的话，就需要内置规则了。现在手机上的设置页面，Lastpass, uBlock都很不好看，没有为移动版适配。

**Comment by ivysrono** [comment]
可能更应该学的是 dencentraletes

**Comment by fengyc** [comment]
@KrasnayaPloshchad 我之前主要是在 android 上遇到的问题是无法打开配置页面， android 上的 webextension 不支持 runtime.openOptionsPage，或 tab.create 这两个 api，但目前现在看有点希望，看文档 tab.create 在 firefox for android 54 上像是要支持了，但是--**文档只能信一半**

**Comment by KrasnayaPloshchad** [comment]
@fengyc Firefox for Android 已经出了 54beta 版，去他们 FTP 服务器下载安装再试试看吧

**Comment by KrasnayaPloshchad** [comment]
大家可以尝试把下列地址加为书签，然后打开配置：
moz-extension://15c8ffc3-7264-4b3d-b6bf-129b01820218/options/options.html

**Comment by KrasnayaPloshchad** [comment]
我在[这里](https://addons.mozilla.org/zh-CN/firefox/addon/urlredirector/versions/)下载了 1.3.5 版本，用 FF 55.0 的安卓版，能看到菜单，但是打不开选项。

**Comment by KrasnayaPloshchad** [comment]
发现有一个办法可以打开配置界面，不管电脑手机都能搞定。

1. 打开 about:config 页面（电脑上要点击“我了解此风险！”才能进去）
2. 输入 extensions.webextensions.uuids，找到这个首选项以后双击这个首选项的值，找到下列文字：
```{"URLRedirector@fengyc":"56c6c553-ff92-4f4a-a4fa-f570b75babfe"}```
其中的数字和字母组合就是 uuid，不同电脑或手机上安装这类扩展时候浏览器分配的 uuid 都是不一样的
4. 利用这段 id 在地址栏里面输入下列地址就能进入配置界面
```moz-extension://56c6c553-ff92-4f4a-a4fa-f570b75babfe/options/options.html```

**Comment by KrasnayaPloshchad** [comment]
Firefox 57 可以打开配置页面了。

**Comment by KrasnayaPloshchad** [comment]
Firefox for android 已经更新到 57，可以完美运行这个扩展了
