### ISSUE TITLE
关于 CORS 的问题

### ISSUE THREAD

**Issue by outloudvi** [fengyc/URLRedirector#40]
替换 cdnjs.cloudflare.com 域名至国内反代后，在访问 cdnjs.com 时会出现 js 无法加载的状况。

返回的 console log 类似于：
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/orange/pace-theme-minimal.min.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
None of the “sha256” hashes in the integrity attribute match the content of the subresource.
```

看起来似乎是因为 CORS 的问题...

**Comment by KrasnayaPloshchad** [comment]
现在碰到这种情况可以通过安装插件解决，火狐插件官网就可以搜索到：
https://addons.mozilla.org/zh-CN/firefox/search/?q=CORS&type=extension

**Comment by outloudvi** [comment]
Emm... 看了一下，两边（cdnjs.cloudflare.com 和我所测试的国内源 cdnjs.loli.net）都是 `access-control-allow-origin: *`，所以其实这似乎是个 [Firefox 的 bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965)。

在这条 bug 中，[这条 comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965#c2)给出了一个似乎可行的用于 Firefox 的临时方案（已提交为 #42）。

**Comment by outloudvi** [comment]
Closing since related Firefox bug is fixed.
