### ISSUE TITLE
无法下载在线规则

### ISSUE THREAD

**Issue by dyxang** [fengyc/URLRedirector#44]
插件版本：1.3.10
Chrome版本： 73.0.3683.103（正式版本） 64 位，目前最新版本
插件安装方式：谷歌插件商店 
问题：点进下载在线规则就一直显示正在下载，重启也没有用

**Comment by fengyc** [comment]
你好，麻烦你把 console 里面的错误日志贴出来，google 商店上的版本很久没有更新了，fq 不方便，你可以试下直接下 release 里面的 chrome 版本，解压就可以以开发者模式加载使用

**Comment by dyxang** [comment]
@fengyc 你好，控制台只显示以下内容

`options.html:339 GET chrome-extension://maolmdhneopinciaokgohljhpdedekee/static/js/jquery.blockUI.js net::ERR_FILE_NOT_FOUND
`

**Comment by dyxang** [comment]
@fengyc 以及在浏览器插件页面显示的错误 
1.
![](https://pic.superbed.cn/item/5cc44a5e3a213b04171a96d8)
![](https://pic.superbed.cn/item/5cc44a893a213b04171a99bf)
![](https://pic.superbed.cn/item/5cc44a953a213b04171a9aa9)
2.
![](https://pic.superbed.cn/item/5cc44aac3a213b04171a9c10)
![](https://pic.superbed.cn/item/5cc44ab83a213b04171a9cdb)

**Comment by fengyc** [comment]
@dyxang 规则定义的 json 里面少了个 enable 字段，请问你用的是那个，麻烦把 url 贴一下，我帮你看看

**Comment by dyxang** [comment]
@fengyc  你好，使用release最新版后仅出现以下问题
![E3ecYq.png](https://s2.ax1x.com/2019/04/29/E3ecYq.png)
![E3e6kn.png](https://s2.ax1x.com/2019/04/29/E3e6kn.png)
![E3esTs.png](https://s2.ax1x.com/2019/04/29/E3esTs.png)

**Comment by KrasnayaPloshchad** [comment]
这个问题已在 Firefox 上面解决了，但这更新没有同步到 Chrome 应用店上面，还望 @gloomy-ghost 出手相助。

**Comment by gloomy-ghost** [comment]
已更新

**Comment by KrasnayaPloshchad** [comment]
问题已解决

**Comment by dyxang** [comment]
@fengyc  你好，更新后下载仍显示“正在下载在线规则...”
建议添加批量本地导入功能。
……完全不知道是什么问题，电脑能访问github……console也没什么信息……能让我先把json文件下载到本地再导入么……

**Comment by KrasnayaPloshchad** [comment]
那您不妨试试 [jsDelivr 镜像](https://cdn.jsdelivr.net/gh/fengyc/URLRedirector@master/tools/rules.json)

**Comment by dyxang** [comment]
@KrasnayaPloshchad  感谢，问题已解决
