### ISSUE TITLE
正则匹配测试正常，但是打开地址不工作

### ISSUE THREAD

**Issue by Tback1** [fengyc/URLRedirector#45]
地址示例  https://apps.apple.com/ca/app/keyboard-maestro-control/id298045982?l=fr
原始地址 (ht|f)tp(s?):\/\/apps.apple.com\/.*?\/
目标地址 https://apps.apple.com/cn/
![image](https://user-images.githubusercontent.com/8872546/65133370-11e73e00-da35-11e9-9bf5-3fea2b4ba41a.png)

地址示例  https://avmoo.net/cn/movie/f9fad9ca70773497
原始地址 (ht|f)tp(s?)\:\/\/avmoo.(.*?)\/
目标地址 https://avmoo.asia/
![image](https://user-images.githubusercontent.com/8872546/65133464-3e02bf00-da35-11e9-9288-ac1b8e5b1f41.png)

插件是正常工作的，随便测试了一个不用匹配的1.com替换为baidu.com是正常工作的。
既然测试地址替换都正常，为什么没起作用呢？
 
工作环境 Chrome 版本 77.0.3865.75（正式版本） （64 位）

**Comment by fengyc** [comment]
@Tback1  进入死循环了，如果第一个要改为正则表达式要替换掉 .com 和 app 之间为 cn ，要改为
原始 `http(s?)://apps.apple.com/(?!cn)\w+/(.*)`
目标 `https://apps.apple.com/cn/$2`

第二个类似地，把 .net / .com 改为 .asia 的话，应该是 `xxx\.(?!.asia)\w+/.* ` 

这里要使用到正则表达式的负前瞻

**Comment by Tback1** [comment]
> @Tback1 进入死循环了，如果第一个要改为正则表达式要替换掉 .com 和 app 之间为 cn ，要改为
> 原始 `http(s?)://apps.apple.com/(?!cn)\w+/(.*)`
> 目标 `https://apps.apple.com/cn/$2`
> 
> 第二个类似地，把 .net / .com 改为 .asia 的话，应该是 `xxx\.(?!.asia)\w+/.* `
> 
> 这里要使用到正则表达式的负前瞻

谢谢指点，但是apple通过了
第二条 
原始 https(s?)://avmoo\.(?!.asia).\w+(/.*)
目标 https://avmoo.asia$2
![image](https://user-images.githubusercontent.com/8872546/65176345-2e13cb00-da87-11e9-9fda-8d49fef49197.png)

用\.(?!.asia).\w 匹配了一个结尾不是asia的\w 任意字符 到/位置，让后再跟上(/.*)

另外，如果URLr本身的匹配测试是无效的，边界容易溢出，那用什么测试比较接近？
我用 https://regex101.com/r/LXLybb/5 识别的匹配是能工作的。为了显示用的python的处理结果。看说明URLr应该是按照JavaScript的匹配，但是俺JS的处理/得转义为\/才能识别，这点又不符合了

**Comment by fengyc** [comment]
主要是匹配的规则要处理好，让处理后的结果不会被匹配到，否则浏览器会进入到死循环。

里面的正则表达式是用 RegExp 对象作了个简单的包装，全局模式，可以直接在浏览器的 console 里面测试。

js 用使用字面量方式时要对 / 进行转义，RegExp 对象不需要：
```
reg1 = /\/\/www/g;
reg2 = new RegExp("//www", "g");
```
两种都可以

**Comment by Tback1** [comment]
> 主要是匹配的规则要处理好，让处理后的结果不会被匹配到，否则浏览器会进入到死循环。
> 
> 里面的正则表达式是用 RegExp 对象作了个简单的包装，全局模式，可以直接在浏览器的 console 里面测试。
> 
> js 用使用字面量方式时要对 / 进行转义，RegExp 对象不需要：
> 
> ```
> reg1 = /\/\/www/g;
> reg2 = new RegExp("//www", "g");
> ```
> 
> 两种都可以

明白了
但是第二条替换avmoo这个依然是没通过的，我试了两种思路都没搞定

前边一种就是按照你的思路利用负向零宽断言匹配到https://avmoo.net的最后一位位置后，将这个整体替换https://avmoo.asia. 这个思路是最合适的，但是也没成功

原始 **https(s?)://avmoo.(?!.asia).\w+(/.*)**
目标 **https://avmoo.asia$2**

让后另外一种我就考虑模仿第一个替换apple语句只替换中间的net为asia，这个写作
原始 **.(?!.asia)\w+(/.*)**
目标 **.asia$1**
但是也没成功

![image](https://user-images.githubusercontent.com/8872546/65223856-a06ec480-daf4-11e9-8e02-4b4921be8398.png)

**Comment by Tback1** [comment]
另外，我没做过前端开发，对Chrome和FF的console谈不上熟悉，按照Chrome的开发文档说明
/pattern/flags
new RegExp(pattern[, flags])
RegExp(pattern[, flags])

我试了一下
![image](https://user-images.githubusercontent.com/8872546/65226658-d06c9680-daf9-11e9-99bd-9cb05b4af454.png)
 结果是一脸懵逼啊~

**Comment by Tback1** [comment]
刚才升级到版本 77.0.3865.90（正式版本） （64 位）后出了一个奇怪的问题~
`https://apps.apple.com/us/app/idays-elegant-countdown/id1007007017`
无法替换其中的us
再一测试
`https://apps.apple.com/ca/app/keyboard-maestro-control/id298045982?l=fr`
等都不工作了

**Comment by fengyc** [comment]
mac 下相同的 chrome 版本，用 
```
https?://apps.apple.com/(?!cn)\w+/(.*)
https://apps.apple.com/cn/$1
```
工作正常

**Comment by Tback1** [comment]
> :-) 我也不是专做前端，兴趣而已。
> 
> mac 下相同的 chrome 版本，用
> 
> ```
> https?://apps.apple.com/(?!cn)\w+/(.*)
> https://apps.apple.com/cn/$1
> ```
> 
> 工作正常
> 
> 另外 asia 那里是我前面写错了，多了个 `.`，应该是 `xxx\.(?!asia)\w+/xxx` 到 `xxx\.cn/xxx`

apple这段代码在chrome  77.0.3865.75上工作正常 在77.0.3865.90 上就失效了
asia替换这段怎么都没成功过。

但是同样的代码
换到 另外一个插件上工作现在很正常~ 这应该是两个插件对正则处理的差异造成的了。
![image](https://user-images.githubusercontent.com/8872546/65373064-db1a5d80-dcaa-11e9-91ad-323c2275d45f.png)

**Comment by fengyc** [comment]
应该是匹配的范围太大了，导致了部分的资源没有加载上来，我试了下 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/4906850/65398326-0f943380-dde9-11e9-92e5-bdaed6c0ea63.png">

是可以的

**Comment by fengyc** [comment]
77.0.3865.90，后面 asia 也可以

<img width="609" alt="image" src="https://user-images.githubusercontent.com/4906850/65398455-ea53f500-dde9-11e9-808c-45728445ad20.png">

Redirector 我之前也看过那部分的源代码，多了个通配符的处理方式，这种方式可以用正则表达式处理

**Comment by Tback1** [comment]
> 77.0.3865.90，后面 asia 也可以
> 
> <img alt="image" width="609" src="https://user-images.githubusercontent.com/4906850/65398455-ea53f500-dde9-11e9-808c-45728445ad20.png">
> 
> Redirector 我之前也看过那部分的源代码，多了个通配符的处理方式，这种方式可以用正则表达式处理

只要能工作，都好。看了你新写的匹配，我大致猜测两者的差异就是对贪婪匹配的长度的处理有区别
Redirector 在这方面工作的宽容度更高一些
而URLRedirector按照这次你最终给出的代码，也就是在断言之后还需要跟上一些特征的部分才能比较好的识别到。

**Comment by Tback1** [comment]
总而言之，谢谢指点~~
