### ISSUE TITLE
能否对重定向的URL做出类型区分

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#5]
比方说区分纯地址栏地址/页内图片/脚本/等等。
有些东西，比方说谷歌图片外链，我只想在地址栏时显示原图，重定向页内元素的话会导致页面布局混乱。

**Comment by fengyc** [comment]
OK，这个是可以实现的，工程量比较大

**Comment by ivysrono** [comment]
https://github.com/einaregilsson/Redirector
可以参考下。

其实仅就实现规则的强大而言，HttpsEverywhere>=Redirector>URLRedirector.
只是Redirector作者维护起来太不方便了，扩展作者也已经甩手不管了。

**Comment by fengyc** [comment]
v1.2.10 已实现，待审核

**Comment by ivysrono** [comment]
终于收到推送了。
但没有看到编写在线规则的文档。由于没有导出功能，所以不能依样画葫芦，无从下手。
拜个晚年，新年快乐！

**Comment by fengyc** [comment]
@ivysrono OK，我会在 tools 目录下补上个样例

**Comment by ivysrono** [comment]
啊，谢谢。
BTW，Chrome没上架？

**Comment by fengyc** [comment]
chrome 那边我虽然在测试，但没有上架，chrome 商店那边有墙隔着，暂时没有弄

**Comment by ivysrono** [comment]
https://raw.githubusercontent.com/ivysrono/URLRedirectorRules/master/fullText.json
我会把之前写的Redirector规则逐步迁移到这里。
你觉得有合适的可以放到项目说明当中。
非常感谢！

**Comment by ivysrono** [comment]
发现个问题：资源类型太多了，在线规则能否给个 [ALL] 这种写法？

**Comment by fengyc** [comment]
谢谢

**Comment by fengyc** [comment]
@ivysrono 你可以 fork 一下，然后把规则放到 tools 目录下，然后向我发一个 pull request 吗？

**Comment by ivysrono** [comment]
这事我之前犹豫过。
因为我可能要大量修改readme来提供测试链接，如果fork恐怕不是很方便，毕竟我对git的各种分支操作很不熟练。
而且我想了下，扩展本身又不集成规则，最多将来搞成ublock那样，那么我自己开一个，大家都自由，订阅者更新也快。
当然我的考虑可能很不成熟，敬请指正。

**Comment by fengyc** [comment]
:-) 该好好了解一下 git 的分支模型

AMO 的审核很耗时间，快的一个星期在右，有次要一个月才能通过，通过在线更新规则是目前更好的选择，也更加灵活，缺点是对缺少计算机知识的用户不太友好。

**Comment by ivysrono** [comment]
在给 HTTPS Everywhere 写规则的这一年多，认识一位朋友，水平不知道比我高到哪里去了～
今天聊到你这目前最好的重定向扩展，他是 Chrome 用户，也没有墙的问题，有现成的 Chrome 开发者账号，愿意帮忙传到扩展库。
虽说是 MIT 但还是希望你委托或授权。
不知意下如何？

**Comment by fengyc** [comment]
非常感谢，我需要点时间整理一下代码，做一些 chrome 的兼容性测试，然后麻烦你们了 #16
