### ISSUE TITLE
兼容Decentraleyes

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#6]
Decentraleyes 直接将部分常用库存在本地，避免了网络请求，比各种重定向都彻底。
现在如果重定向到科大镜像，就浪费了，能否做到让Decentraleyes优先适用？

**Comment by fengyc** [comment]
谢谢你的建议，把 cdn 上的 js 缓存到本地是个很好的想法，firefox 的 webextension 现在可以检查已安装的扩展，但我目前不能确定能否实现你想要的功能，我需要查一下看看能不能实现。

**Comment by fengyc** [comment]
在 #7 中讨论
