### ISSUE TITLE
为何同样的规则，本地有效，在线就无效？

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#8]
Win10 x64
Firefox x64 50.1.0
URLRedirector 1.2.9
https://raw.githubusercontent.com/ivysrono/URLRedirector/master/tools/fullText.json
![snipaste](https://cloud.githubusercontent.com/assets/2649544/21268026/e0c9f206-c3e7-11e6-931a-fd4374e85604.png)

已经新建配置试过了，问题依旧。

**Comment by fengyc** [comment]
谢谢，这里可能有 bug ，我在查

**Comment by fengyc** [comment]
在线规则使用 json 解析，这个规则文件有 json 字符串转义的问题，可以试试 [json在线校验](http://www.json.cn/) 工具

**Comment by ivysrono** [comment]
多谢多谢，终于成功了！
接下来就等待 android 版的上线了~
