### ISSUE TITLE
规则执行之疑问

### ISSUE THREAD

**Issue by ivysrono** [fengyc/URLRedirector#9]
订阅这条规则：
https://raw.githubusercontent.com/ivysrono/URLRedirectorRules/master/gooreplacerWithDecentraleyes.json

生效后就很奇怪了，大多数测试都很快捷，如：
https://themes.googleusercontent.com/static/fonts/antic/v4/hEa8XCNM7tXGzD0Uk0AipA.ttf
https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

但部分测试完全不成功，空白页面一直转圈，如：
https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js

这是为什么？是不是排除规则导致的问题？

另外，正则表达式与简单规则对比，会不会有性能上的差距？

**Comment by fengyc** [comment]
OK，我测试一下。从性能上看应该是没有很多的差距，执行那一点正则表达式的开销其实不多的，就测试情况来看，在 macbook 上千个正则表达式才带来极少的延迟（用随机生成的url）。

**Comment by ivysrono** [comment]
昨天晚上几个小时也没搞明白为何排除规则生效后主规则就失效了…

**Comment by fengyc** [comment]
已经定位 bug

**Comment by ivysrono** [comment]
1.2.13 重定向成功。
Thanks.

**Comment by ivysrono** [comment]
@fengyc 我把Redirector中的规则基本迁移完成了，大多在 https://raw.githubusercontent.com/ivysrono/URLRedirectorRules/master/Directly.json
大多成功，就以下几条有问题。
怀疑是正则解析方法与Redirector不同。
麻烦指点下。
```
    {
      "description": "GreasyFork强制简体中文——会把测试地址中的scripts吃掉",
      "exampleUrl": "https://greasyfork.org/zh-TW/scripts/1-greasemonkey-test-style",
      "origin": "^https://greasyfork.org/((?!zh-CN).)+/",
      "types": ["main_frame"],
      "target": "https://greasyfork.org/zh-CN/",
      "enable": true
    },
    {
      "description": "AMO强制简体中文——毫无反应",
      "exampleUrl": "https://addons.mozilla.org/zh-tw/firefox/",
      "origin": "^https://addons.mozilla.org/((?!zh-CN).)+/firefox/",
      "types": ["main_frame"],
      "target": "https://addons.mozilla.org/zh-CN/firefox/",
      "enable": true
    },
    {
      "description": "去除AMO后缀——毫无反应",
      "exampleUrl": "https://addons.mozilla.org/zh-CN/firefox/addon/omnisidebar/?src=hp-dl-featured",
      "origin": "^https://addons.mozilla.org/zh-CN/firefox/addon/(.+)/\\?src=.*",
      "types": ["main_frame"],
      "target": "https://addons.mozilla.org/zh-CN/firefox/addon/$1",
      "enable": true
    },
    {
      "description": "去除优酷来源后缀——无限白屏转圈",
      "exampleUrl": "http://v.youku.com/v_show/id_XMTY0MjIyMDU3Mg==.html?from=y1.2-1-105.3.5-2.1-1-1-4-0",
      "origin": "v.youku.com/v_show/id_(\\w+)(==_?.*)?.html(\\?from=.*)?$",
      "types": ["main_frame"],
      "target": "v.youku.com/v_show/id_$1.html",
      "enable": true
    },
```

**Comment by ivysrono** [comment]
尝试修复过程中又发现了个奇怪问题。下面这条规则，只能处理第一条测试，第二条这种最后带个 / 的就会出错。水平有限，试了半天解决不聊。
```
    {
      "description": "跳过微博看看框架",
      "exampleUrl": "http://weibo.wbdacdn.com/url/t/R5mLykn",
      "exampleUrl": "http://weibo.wbdacdn.com/url/t/RIo18YK/",
      "origin": "weibo.wbdacdn.com/url/t/(\\w{7})",
      "types": ["main_frame"],
      "target": "t.cn/$1",
      "enable": true
    },
```

**Comment by fengyc** [comment]
第一个应该是正则表达式的问题， ".)+" 这个地方把 scripts 也包含进来了
第二和第三个让我有点费解，两条规则都是已经转换到 zh-CN 并返回的，但是 firefox 似乎没有处理，可能是有些特别的地方我没有注意到

**Comment by ivysrono** [comment]
今天在测试中发现，这两条规则在Redirector上也是无效的。
不知道是哪里的坑了。

**Comment by fengyc** [comment]
未解问题，URLRedirector 已做了重定向，但是 firefox 未有处理

**Comment by ivysrono** [comment]
把所有规则更新到了 1.3.1 格式。
把不能生效的两条规则单独拿了出来：https://raw.githubusercontent.com/ivysrono/URLRedirectorRules/master/AMO.json

**Comment by fengyc** [comment]
已向 mozilla 报 bug : https://bugzilla.mozilla.org/show_bug.cgi?id=1344095

**Comment by fengyc** [comment]
mozilla 的回复 https://bugzilla.mozilla.org/show_bug.cgi?id=1334918#c10
对于某些host的URL是不能修改的，包括：
addons.mozilla.org
discovery.addons.mozilla.org
testpilot.firefox.com
所以暂时没有办法做这个规则的重定向

**Comment by ivysrono** [comment]
算了，也不是必须的。
Mozilla学Google，真是越来越像了……

**Comment by ivysrono** [comment]
根据政策，所有的 WebExtension 都不能处理 AMO 等域名。
